---
# tasks file for management

- name: Build management | Configure Vagrantfile
  include: buildVagrant.yml
  when:  user_infrastructure

- name: Deploy management | Vagrant Up
  include: deployvagrant.yml
  when:  user_infrastructure and not destroy

- name: Destroy management |  Vagrant Destroy
  include: vagrantdestroy.yml
  when: destroy and user_infrastructure
