
vagrant_dir: /Users/femistone/devops/infrastructure
user_infrastructure: true
destroy: false


# Virtual Servers Infrastructure
dc1: london
dc2: paris
opt_dir: /opt
owner: prod
working_dir: "{{ vagrant_dir }}/{{ owner }}"
dc_deploy_type: single # Other accepted value is "dr"
vm_image: ubuntu/trusty64     #geerlingguy/centos7

#Networking
cidr: 192.168.2 # accepted values are the first 3 part of an IP address

#Jenkins
jenkins_vm_memory: 8192
jenkins_vm_cpu: 2

#ldap
ldap_vm_memory: 3072
ldap_vm_cpu: 2

#management
management_vm_memory: 2048
management_vm_cpu: 2

#Master
master_vm_memory: 2048
master_vm_cpu: 2
master_vm_count: 3

#Worker
worker_vm_memory: 2048
worker_vm_cpu: 2
worker_vm_count: 3
