---
# tasks file for worker-nodes

- name: Build Workers | Configure Vagrantfile
  include: buildVagrant.yml
  when:  user_infrastructure 

- name: Deploy Workers | Vagrant Up
  include: deployvagrant.yml
  when:  user_infrastructure and not destroy

- name: Destroy Masters |  Vagrant Destroy
  include: vagrantdestroy.yml
  when: destroy and user_infrastructure
