---
# tasks file for k8s Masters

- name: Build Masters | Configure Vagrantfile
  include: buildVagrant.yml
  when:  user_infrastructure 

- name: Deploy Masters | Vagrant Up
  include: deployvagrant.yml
  when:  user_infrastructure and not destroy

- name: Destroy Masters |  Vagrant Destroy
  include: vagrantdestroy.yml
  when: destroy and user_infrastructure
